#!/bin/sh
while read file
do
    case "$1" in
        "w") 
            cp "$file" ~/.config/wall && feh --bg-scale --no-fehbg ~/.config/wall ;;
        "d")
            [ "$(printf "No\\nYes" | dmenu -i -p "Really delete $file?")" = "Yes" ] && rm "$file" && notify-send "$file deleted." ;;
        "t")
            trash-put "$file" ;;
        "r")
            convert -rotate 90 "$file" "$file" ;;
        "R")
            convert -rotate -90 "$file" "$file" ;;
        "f")
            convert -flop "$file" "$file" ;;
        "i")	
            notify-send "File information" "$(mediainfo "$file")" ;;
    esac
done
