#!/bin/bash 

# cleanup
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export GOPATH="$XDG_DATA_HOME"/go
export DENO_INSTALL="$XDG_DATA_HOME"/deno
export CARGO_HOME="$XDG_DATA_HOME"/cargo
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
export LESSHISTFILE="$XDG_DATA_HOME"/lesshst
export MYSQL_HISTFILE="$XDG_DATA_HOME"/mysql_history
export ZDOTDIR="$XDG_CONFIG_HOME"/zsh
export INPUTRC="${XDG_CONFIG_HOME:-$HOME/.config}/shell/inputrc"
export WGETRC="$XDG_CONFIG_HOME"/wget/wgetrc
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc
export ICEAUTHORITY="$XDG_CACHE_HOME"/ICEauthority
#export XAUTHORITY="$XDG_RUNTIME_DIR"/Xauthority # it doesn't work on dm

# PATH
export PATH="$HOME/.local/bin:$PATH"
export PATH="$(find ~/Documents/scripts/ -type d -printf %p:):$PATH"
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
export PATH="$DENO_INSTALL/bin:$PATH"
export PATH="$CARGO_HOME/bin:$PATH"

# default programs
export TERMINAL="alacritty"
export BROWSER="brave-browser"
export EDITOR="nvim"
export READER="zathura"
export PAGER="less"
export VIDEO="mpv"
export IMAGE="sxiv"
export OPENER="xdg-open"

# programs settings
export FZF_DEFAULT_COMMAND="find ! -path './.cache/*'"
export MOZ_USE_XINPUT2="1"	              # Mozilla smooth scrolling/touchpads.
export QT_QPA_PLATFORMTHEME=qt5ct         # Theme for qt apps

# Turn off Telemetry's
#export DOTNET_CLI_TELEMETRY_OPTOUT=1  # Turn off microsoft telemetry

# source bashrc when login to bash
if [ -n "$BASH_VERSION" ]; then
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi
